Disable cgo by default
cli/gh-extension-precompile pull request #31
Opened 2023-01-22 20:14 UTC by bewuethr

As discussed in #29, this disables cgo by default. To avoid making it impossible to override &ndash; maybe somebody builds their extension for exactly one architecture and does want to use cgo for it &ndash; it's not hard-coded in the environment, but set as an optional input parameter that defaults to `0`.

Closes #29

2023-01-23 16:14 UTC, mislav requested changes

2023-01-23 16:14 UTC, mislav commented on README.md
> +          cgo_enabled: 1
Since the CGO_ENABLED environment variable is already a known mechanism, should we just instead instruct users to set the environment variable instead of exposing an additional action input?
```suggestion
        env:
          - CGO_ENABLED=1
```
Then, if the workflow hasn't set a value, our built-in build script can set a default value:
```sh
export CGO_ENABLED="${CGO_ENABLED:-0}"
```
What do you think?

2023-01-23 17:00 UTC, bewuethr commented on README.md
> +          cgo_enabled: 1
Ah, yes, that's more elegant and enables overriding, which was the reason to introduce an input parameter in the first place. I'll update.

2023-01-26 05:34 UTC, bewuethr commented
I see you usually merge without squashing, should I squash the commits in my branch?

2023-01-26 16:41 UTC, mislav approved these changes
Looks good! Pushed some light tweaks. Don't worry about squashing; we do so at merge time.

2023-01-26 16:42 UTC, merged